CREATE TABLE role (
                      id   BIGINT       PRIMARY KEY,
                      name VARCHAR(50)  NOT NULL
);

CREATE TABLE users (
                       id              BIGINT         PRIMARY KEY,
                       username        VARCHAR(50)    NOT NULL UNIQUE,
                       first_name      VARCHAR(100)   NOT NULL,
                       last_name       VARCHAR(100)   NOT NULL,
                       email           VARCHAR(150)   NOT NULL UNIQUE,
                       password        VARCHAR(255)   NOT NULL,
                       date_of_birth   DATE           NOT NULL,
                       enabled         BOOLEAN        NOT NULL,
                       gender          VARCHAR(10),
                       bio             TEXT
);

CREATE TABLE user_roles (
                            user_id BIGINT        NOT NULL,
                            role    VARCHAR(50)   NOT NULL,
                            PRIMARY KEY (user_id, role),
                            FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_allowed_access (
                                     user_id         BIGINT      NOT NULL,
                                     allowed_username VARCHAR(50) NOT NULL,
                                     PRIMARY KEY (user_id, allowed_username),
                                     FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE trip (
                      id                    VARCHAR(50)   PRIMARY KEY,
                      user_id               BIGINT        NOT NULL,
                      destination           VARCHAR(100)  NOT NULL,
                      description           VARCHAR(255),
                      start_date            DATE          NOT NULL,
                      end_date              DATE          NOT NULL,
                      budget_home_currency  DECIMAL(12,2) NOT NULL,
                      budget_local_currency DECIMAL(14,2) NOT NULL,
                      home_currency_code    CHAR(3)       NOT NULL,
                      local_currency_code   CHAR(3)       NOT NULL,
                      FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE expense (
                         id             BIGINT        PRIMARY KEY,
                         trip_id        VARCHAR(50)   NOT NULL,
                         description    VARCHAR(255),
                         amount_local   DECIMAL(14,2) NOT NULL,
                         amount_home    DECIMAL(12,2) NOT NULL,
                         date           DATE          NOT NULL,
                         time_stamp     TIMESTAMP     NOT NULL,
                         category       VARCHAR(50),
                         FOREIGN KEY (trip_id) REFERENCES trip(id)
);

CREATE TABLE wishlist_item (
                               id             VARCHAR(20)   PRIMARY KEY,
                               trip_id        VARCHAR(50)   NOT NULL,
                               description    VARCHAR(255),
                               amount_local   DECIMAL(14,2) NOT NULL,
                               amount_home    DECIMAL(12,2) NOT NULL,
                               purchased      BOOLEAN       NOT NULL,
                               category       VARCHAR(50),
                               FOREIGN KEY (trip_id) REFERENCES trip(id)
);

CREATE TABLE images (
                        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id      BIGINT              NOT NULL,
                        image_name   VARCHAR(100)        NOT NULL,
                        image_type   VARCHAR(255),
                        image_data   BYTEA,
                        CONSTRAINT fk_images_user
                            FOREIGN KEY (user_id)
                                REFERENCES users(id)
                                ON DELETE CASCADE
);
